### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-value-resolve-transform#1]
**Current Behavior**
The same value can be inputted in multiple ways, making it seem that they are distinct when in fact, they represent the same value. This is especially true with user inputted data and very relevant to any survey source (e.g. SurveyGizmo, SurveyMonkey, Typeform).

**Desired Behavior**
The integration takes in a field name, an array of potential origin values, and the desired value to replace them with.

**Example config**
```
config: {
"field": "city"
"originValue": ["New York","NYC","New York City","New York, New York", "nyc"]
"resolvedValue": "new york"
}
```

**Comment by dansweet1** [comment]
Working on this. Found a config-js library that may help.

**Comment by benjamingregory** [comment]
@dansweet1 I left this out of the description by mistake but the config should also be able to handle multiple fields.

**Comment by dansweet1** [comment]
Wrote some TODO's for this transform yesterday after talking to Mike. Since he's on his Dark Side day I don't expect feedback. (If you have time take a look and see if I'm far off from what I need) I looked at Trong's transform for Typeform and was thinking some aspects were similar.

**Comment by benjamingregory** [comment]
@dansweet1 Please push up any code you have.

**Comment by dansweet1** [comment]
Showed Alois what I had yesterday and he gave me some pseudo code for a better idea of how to do this. Talking with Mike today as well about Transforms/bouncing some questions I had off of him.

**Comment by dansweet1** [comment]
Continuing development on here. Going to try and use one of the Survey API's to test this (let me know if you think that's a good strategy).

**Comment by dansweet1** [comment]
After talking with Ryan we decided the most efficient approach is to make the entire config an array that allows it to accept multiple fields (as well as possible values and resolved value), in the main method have a function(config, object){ loop through properties(config) and inside of their if the object exists in those properties, accept the value. If the input exists in the possible values  and needs resolved, resolve input to match.

**Comment by dansweet1** [comment]
Trong helped with making my method more concise(importing lodash when node has it's own iterating function, messy logic) but it's still not referencing my config for the matching the input values with the array in my config and I'm trying to figure it out myself. Working on matching it with the config and then writing tests.

**Comment by benjamingregory** [comment]
@dansweet1; @perryao pointed out that the example config I used was misleading.

This revised one is more in line with what I was thinking in supporting multiple fields:
```
config: {
"fields": [{
   "field": "city",
   "originValue": ["New York","NYC","New York City","New York, New York", "nyc"],
   "resolvedValue": "new york"
   }, {
  "field": "state",
  "originValue": ["GA","Georgia","GEORGIA"],
  "resolvedValue": "georgia"
  }]
}
```

**Comment by dansweet1** [comment]
^^^ I had been using that as the format in the config after talking to Trong the other day but thank you for clarifying.

**Comment by dansweet1** [comment]
2/2/17 I have to implement 2 more tests, documentation (README & commenting within lib/index.js), and per @perryao 's suggestion look further into the logic he helped me with 2/1/17. I did not fully understand the use of mapping/streams when Mike was going over it. He also had mentioned to follow Arrange>Act>Assert  when writing tests. Submitting PR at EOD 2/2/17 and moving on to the IP-Address Activity.
